# 📊 Predicting the Impact of USD and JPY Economic News on the USD/JPY Currency Pair

## 1. Project Overview

The foreign exchange (Forex) market is highly sensitive to macroeconomic news releases. High-impact economic announcements from the United States and Japan, such as interest rate decisions, inflation reports, GDP releases, employment statistics, and central bank communications, often lead to significant movements in the USD/JPY Pair.

This project investigates how historical USD and JPY economic news events influence the price movement of the USD/JPY currency pair. By combining historical economic news data with minute-level market price data, the project measures market reactions before, during, and after each news release.

The insights gained from this analysis will be used to build predictive models capable of estimating possible market reactions to future economic announcements.
    

# 2. Problem Statement

Economic news plays a crucial role in the Forex market, yet traders often rely on experience or manual analysis to estimate its impact. There is limited quantitative analysis that measures how specific USD and JPY news events influence the USD/JPY exchange rate over different time intervals.

This project seeks to bridge that gap by collecting historical economic news and market price data, aligning them based on their release times, and analyzing the resulting price movements to uncover meaningful patterns.


# 3. Project Objectives

* Collect historical USD and JPY economic news.
* Collect historical USD/JPY minute-level price data.
* Clean and preprocess both datasets.
* Align economic news with corresponding market prices.
* Extract the market price:

  * 5 minutes before the news release
  * At the exact release time
  * 5 minutes after the release
  * 24 hours after the release
  * 48 hours after the release
* Analyze how different economic events affect the USD/JPY.
* Build predictive models capable of estimating potential market reactions to future economic news releases.


# 4. Datasets

### Economic News Data

Contains:

* News release date
* Release time
* Currency
* Economic event
* Actual value
* Forecast value
* Previous value

### Price Data

Contains minute-level USD/JPY market prices:

* Datetime
* Open
* High
* Low
* Close

Only the Close price is retained for this project because it represents the final traded price for each minute and is used to measure the market"s reaction to news events.


# 5. Tools and Technologies

### Programming Language

* Python

### Libraries

* pandas
* NumPy
* requests
* BeautifulSoup
* datetime
* pathlib
* matplotlib
* seaborn
* scikit-learn
* XGBoost (for modeling)
* SHAP (for model explainability)

### Development Environment

* Jupyter Notebook
* Visual Studio Code

### Version Control

* Git
* GitHub



# 6. Expected Output

The final dataset will contain the following information for each economic news event:

* News release details
* Actual and Previous economic values
* USD/JPY Close price 5 minutes before the release
* USD/JPY Close price at the release
* USD/JPY Close price 5 minutes after the release
* USD/JPY Close price 24 hours after the release
* USD/JPY Close price 48 hours after the release

This structured dataset will serve as the foundation for exploratory data analysis, feature engineering, and predictive modeling.
    

# 8. Project Workflow

```text
Problem Definition
        │
        ▼
Data Collection
        │
        ▼
Data Cleaning
        │
        ▼
Data Integration
        │
        ▼
Feature Engineering
        │
        ▼
Exploratory Data Analysis
        │
        ▼
Machine Learning
        │
        ▼
Model Evaluation
        │
        ▼
Model Interpretation
        │
        ▼
Deployment
```

In [59]:
##importing used packges
import pandas as pd
import numpy as np

In [60]:
#importing the news data


data = pd.read_csv("./Data/forex_factory_2024_events.csv")

In [61]:
#viewing top 5 of our news data

data.head()

,day,month,year,date,time,currency,impact,event,actual,forecast,previous
0,NaN,NaN,2024,MonJan 1,All Day,JPY,NaN,Bank Holiday,NaN,NaN,NaN
1,NaN,NaN,2024,MonJan 1,All Day,USD,NaN,Bank Holiday,NaN,NaN,NaN
2,NaN,NaN,2024,TueJan 2,All Day,JPY,NaN,Bank Holiday,NaN,NaN,NaN
3,NaN,NaN,2024,TueJan 2,3:45pm,USD,NaN,Final Manufacturing PMI,47.9,48.4,48.2
4,NaN,NaN,2024,TueJan 2,4:00pm,USD,NaN,Construction Spending m/m,0.4%,0.6%,1.2%

In [62]:
## dropping all columns with time == all day

data = data.drop(data[data["time"] == "All Day"].index)

In [63]:
#viewing top 5 after dropping columns all day

data.head()

,day,month,year,date,time,currency,impact,event,actual,forecast,previous
3,NaN,NaN,2024,TueJan 2,3:45pm,USD,NaN,Final Manufacturing PMI,47.9,48.4,48.2
4,NaN,NaN,2024,TueJan 2,4:00pm,USD,NaN,Construction Spending m/m,0.4%,0.6%,1.2%
6,NaN,NaN,2024,WedJan 3,2:30pm,USD,NaN,FOMC Member Barkin Speaks,NaN,NaN,NaN
7,NaN,NaN,2024,WedJan 3,4:00pm,USD,NaN,ISM Manufacturing PMI,47.4,47.2,46.7
8,NaN,NaN,2024,WedJan 3,NaN,USD,NaN,JOLTS Job Openings,8.79M,8.84M,8.85M

In [64]:
# dropping the impact columns because it is not relevant to our project, we want the model to determine the impact 
## dropping month and day

data = data.drop(columns = ["impact", "month", "day"])

In [65]:
#viewing our data top 5 after dropping the impact, month and day column

data.head()

,year,date,time,currency,event,actual,forecast,previous
3,2024,TueJan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2
4,2024,TueJan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%
6,2024,WedJan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN
7,2024,WedJan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7
8,2024,WedJan 3,NaN,USD,JOLTS Job Openings,8.79M,8.84M,8.85M

In [66]:
## dropping rows where time is NAN

data = data.dropna(subset = ["time"])

In [67]:
## assigning a copy of our data to the data variable
data = data.copy()

In [68]:
data.head()

,year,date,time,currency,event,actual,forecast,previous
3,2024,TueJan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2
4,2024,TueJan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%
6,2024,WedJan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN
7,2024,WedJan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7
11,2024,WedJan 3,8:00pm,USD,FOMC Meeting Minutes,NaN,NaN,NaN

In [69]:
# importing the usd/jpy price data

data_price = pd.read_csv("./Data/DAT_ASCII_USDJPY_M1_2024.csv", sep=";", header=None, names=["Datetime", "Open", "High", "Low", "Close", "Volume"])

In [70]:
#viewing top 5 of the usd/jpy price

data_price.head()

          Datetime     Open     High      Low    Close  Volume
0  20240101 170000  140.843  140.852  140.843  140.852       0
1  20240101 170100  140.852  140.852  140.852  140.852       0
2  20240101 170200  140.850  140.850  140.850  140.850       0
3  20240101 170300  140.840  140.840  140.840  140.840       0
4  20240101 170500  140.841  140.841  140.841  140.841       0

In [71]:
#conveting our data to a datetime object

data_price["Datetime"] = pd.to_datetime(data_price["Datetime"], format="%Y%m%d %H%M%S")

In [72]:
# sorting and making the datetime column the index from 0-end accordingly using the datetime column

data_price = data_price.set_index("Datetime").sort_index()

In [73]:
 ## assigning the close datetime to match the data datetime and returns 0 if it does not match

def get_close_price(target_time):
    try:
        return data_price.loc[target_time, "Close"]
    except KeyError:
        return 0

In [74]:
data_price.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [75]:
## dropping the high, low, open and volume column

data_price = data_price.drop(columns = ["High", "Low", "Open", "Volume"])

In [76]:
data_price.head()

                       Close
Datetime
2024-01-01 17:00:00  140.852
2024-01-01 17:01:00  140.852
2024-01-01 17:02:00  140.850
2024-01-01 17:03:00  140.840
2024-01-01 17:05:00  140.841

In [77]:
data.head()

,year,date,time,currency,event,actual,forecast,previous
3,2024,TueJan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2
4,2024,TueJan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%
6,2024,WedJan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN
7,2024,WedJan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7
11,2024,WedJan 3,8:00pm,USD,FOMC Meeting Minutes,NaN,NaN,NaN

In [78]:
#removing the day from the beginning in the date column

data["date"] = data["date"].str.replace(
    r"^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)",
    "",
    regex=True
).str.strip()

In [79]:
data.head()

,year,date,time,currency,event,actual,forecast,previous
3,2024,Jan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2
4,2024,Jan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%
6,2024,Jan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN
7,2024,Jan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7
11,2024,Jan 3,8:00pm,USD,FOMC Meeting Minutes,NaN,NaN,NaN

In [80]:
## creating a datetime column in the data

data["DateTime"] = pd.to_datetime(
    data["year"].astype(str) + " " +
    data["date"] + " " +
    data["time"],
    format="%Y %b %d %I:%M%p"
)

In [81]:
## converting the news data from UTC +1 TO UTC

data["DateTime"] = (
    data["DateTime"]
    .dt.tz_localize("Etc/GMT-1")
    .dt.tz_convert("UTC")
)

In [82]:
data.head()

,year,date,time,currency,event,actual,forecast,previous,DateTime
3,2024,Jan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2,2024-01-02 14:45:00+00:00
4,2024,Jan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%,2024-01-02 15:00:00+00:00
6,2024,Jan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN,2024-01-03 13:30:00+00:00
7,2024,Jan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7,2024-01-03 15:00:00+00:00
11,2024,Jan 3,8:00pm,USD,FOMC Meeting Minutes,NaN,NaN,NaN,2024-01-03 19:00:00+00:00

In [83]:
## removing the timezone information beside the datetime data

data["DateTime"] = data["DateTime"].dt.tz_localize(None)

In [84]:
data.head()

,year,date,time,currency,event,actual,forecast,previous,DateTime
3,2024,Jan 2,3:45pm,USD,Final Manufacturing PMI,47.9,48.4,48.2,2024-01-02 14:45:00
4,2024,Jan 2,4:00pm,USD,Construction Spending m/m,0.4%,0.6%,1.2%,2024-01-02 15:00:00
6,2024,Jan 3,2:30pm,USD,FOMC Member Barkin Speaks,NaN,NaN,NaN,2024-01-03 13:30:00
7,2024,Jan 3,4:00pm,USD,ISM Manufacturing PMI,47.4,47.2,46.7,2024-01-03 15:00:00
11,2024,Jan 3,8:00pm,USD,FOMC Meeting Minutes,NaN,NaN,NaN,2024-01-03 19:00:00

In [85]:
#if the next two days falls on a weekend, go to the next 2 or next 3 days

def get_close_48_72_96(news_time):

    for hrs in [48, 72, 96]:

        target = news_time + pd.Timedelta(hours=hrs)

        if target in data_price.index:
            return data_price.loc[target, "Close"]

    return 0

In [86]:
#for after 24hrs that falls on weekend use 5 mins

def get_close_24h(news_time):
    # Try 24 hours after
    target_24 = news_time + pd.Timedelta(hours=24)

    if target_24 in data_price.index:
        return data_price.loc[target_24, "Close"]

    # Fallback: 5 minutes after
    target_5 = news_time + pd.Timedelta(minutes=5)

    if target_5 in data_price.index:
        return data_price.loc[target_5, "Close"]

    return 0

In [87]:
## dropping the year, forecast, date and time column

data = data[[
    "DateTime",
    "currency",
    "event",
    "actual",
    "previous"
]]

In [88]:
data.head()

              DateTime currency                      event actual previous
3  2024-01-02 14:45:00      USD    Final Manufacturing PMI   47.9     48.2
4  2024-01-02 15:00:00      USD  Construction Spending m/m   0.4%     1.2%
6  2024-01-03 13:30:00      USD  FOMC Member Barkin Speaks    NaN      NaN
7  2024-01-03 15:00:00      USD      ISM Manufacturing PMI   47.4     46.7
11 2024-01-03 19:00:00      USD       FOMC Meeting Minutes    NaN      NaN

In [95]:
## creating the new columns for the price before, at and after news event

data.loc[:, "Close_5min_before"] = data["DateTime"].apply(
    lambda x: get_close_price(x - pd.Timedelta(minutes=5))
)

data.loc[:, "Close_at_release"] = data["DateTime"].apply(
    get_close_price
)

data.loc[:, "Close_5min_after"] = data["DateTime"].apply(
    lambda x: get_close_price(x + pd.Timedelta(minutes=5))
)

data.loc[:, "Close_24h_after"] = data["DateTime"].apply(
    get_close_24h
)


data.loc[:, "Close_48h_after"] = data["DateTime"].apply(
    get_close_48_72_96
)

In [96]:
data.head(20)

,DateTime,currency,event,actual,previous,Close_5min_before,Close_at_release,Close_5min_after,Close_24h_after,Close_48h_after
3,2024-01-02 14:45:00,USD,Final Manufacturing PMI,47.9,48.2,141.939,141.947,141.990,143.252,144.581
4,2024-01-02 15:00:00,USD,Construction Spending m/m,0.4%,1.2%,141.982,141.952,141.958,143.258,144.567
7,2024-01-03 15:00:00,USD,ISM Manufacturing PMI,47.4,46.7,143.300,143.258,143.167,144.567,144.668
13,2024-01-04 00:30:00,JPY,Final Manufacturing PMI,47.9,47.7,143.617,143.640,143.824,144.674,144.424
14,2024-01-04 12:30:00,USD,Challenger Job Cuts y/y,-20.2%,-40.8%,144.563,144.615,144.647,144.770,143.921
15,2024-01-04 13:15:00,USD,ADP Non-Farm Employment Change,164K,101K,144.598,144.642,144.690,144.817,144.065
16,2024-01-04 13:30:00,USD,Unemployment Claims,202K,220K,144.628,144.618,144.579,144.808,144.105
17,2024-01-04 14:45:00,USD,Final Services PMI,51.4,51.3,144.598,144.581,144.515,144.636,144.126
18,2024-01-04 15:30:00,USD,Natural Gas Storage,-14B,-87B,144.566,144.578,144.566,144.673,144.206
19,2024-01-04 16:00:00,USD,Crude Oil Inventories,-5.5M,-7.1M,144.585,144.609,144.593,144.763,144.135
20,2024-01-04 23:50:00,JPY,Monetary Base y/y,7.8%,8.9%,144.841,144.858,144.832,144.832,144.431
21,2024-01-05 05:00:00,JPY,Consumer Confidence,37.2,36.1,145.155,145.198,145.254,145.254,144.228
30,2024-01-08 20:00:00,USD,Consumer Credit m/m,23.8B,5.8B,143.865,143.924,143.832,144.545,145.462
31,2024-01-08 23:30:00,JPY,Tokyo Core CPI y/y,2.1%,2.3%,143.605,143.634,143.664,144.809,145.362
33,2024-01-09 11:00:00,USD,NFIB Small Business Index,91.9,90.6,144.288,144.331,144.349,145.563,145.945
35,2024-01-09 15:02:00,USD,RCM/TIPP Economic Optimism,44.7,40.0,144.554,144.435,144.418,145.655,145.517
38,2024-01-09 23:30:00,JPY,Average Cash Earnings y/y,0.2%,1.5%,144.840,144.809,144.828,145.362,145.032
39,2024-01-10 03:35:00,JPY,10-y Bond Auction,0.60|2.9,0.70|2.8,144.906,144.954,144.958,145.402,144.979
40,2024-01-10 15:00:00,USD,Final Wholesale Inventories m/m,-0.2%,-0.2%,145.649,145.678,145.653,145.490,144.862
41,2024-01-10 15:30:00,USD,Crude Oil Inventories,1.3M,-5.5M,145.744,145.729,145.696,145.447,144.887

In [97]:
## doping actual or previos with NaN

data = data.dropna(subset = ["actual", "previous"])

In [98]:
data.head(20)

,DateTime,currency,event,actual,previous,Close_5min_before,Close_at_release,Close_5min_after,Close_24h_after,Close_48h_after
3,2024-01-02 14:45:00,USD,Final Manufacturing PMI,47.9,48.2,141.939,141.947,141.990,143.252,144.581
4,2024-01-02 15:00:00,USD,Construction Spending m/m,0.4%,1.2%,141.982,141.952,141.958,143.258,144.567
7,2024-01-03 15:00:00,USD,ISM Manufacturing PMI,47.4,46.7,143.300,143.258,143.167,144.567,144.668
13,2024-01-04 00:30:00,JPY,Final Manufacturing PMI,47.9,47.7,143.617,143.640,143.824,144.674,144.424
14,2024-01-04 12:30:00,USD,Challenger Job Cuts y/y,-20.2%,-40.8%,144.563,144.615,144.647,144.770,143.921
15,2024-01-04 13:15:00,USD,ADP Non-Farm Employment Change,164K,101K,144.598,144.642,144.690,144.817,144.065
16,2024-01-04 13:30:00,USD,Unemployment Claims,202K,220K,144.628,144.618,144.579,144.808,144.105
17,2024-01-04 14:45:00,USD,Final Services PMI,51.4,51.3,144.598,144.581,144.515,144.636,144.126
18,2024-01-04 15:30:00,USD,Natural Gas Storage,-14B,-87B,144.566,144.578,144.566,144.673,144.206
19,2024-01-04 16:00:00,USD,Crude Oil Inventories,-5.5M,-7.1M,144.585,144.609,144.593,144.763,144.135
20,2024-01-04 23:50:00,JPY,Monetary Base y/y,7.8%,8.9%,144.841,144.858,144.832,144.832,144.431
21,2024-01-05 05:00:00,JPY,Consumer Confidence,37.2,36.1,145.155,145.198,145.254,145.254,144.228
30,2024-01-08 20:00:00,USD,Consumer Credit m/m,23.8B,5.8B,143.865,143.924,143.832,144.545,145.462
31,2024-01-08 23:30:00,JPY,Tokyo Core CPI y/y,2.1%,2.3%,143.605,143.634,143.664,144.809,145.362
33,2024-01-09 11:00:00,USD,NFIB Small Business Index,91.9,90.6,144.288,144.331,144.349,145.563,145.945
35,2024-01-09 15:02:00,USD,RCM/TIPP Economic Optimism,44.7,40.0,144.554,144.435,144.418,145.655,145.517
38,2024-01-09 23:30:00,JPY,Average Cash Earnings y/y,0.2%,1.5%,144.840,144.809,144.828,145.362,145.032
39,2024-01-10 03:35:00,JPY,10-y Bond Auction,0.60|2.9,0.70|2.8,144.906,144.954,144.958,145.402,144.979
40,2024-01-10 15:00:00,USD,Final Wholesale Inventories m/m,-0.2%,-0.2%,145.649,145.678,145.653,145.490,144.862
41,2024-01-10 15:30:00,USD,Crude Oil Inventories,1.3M,-5.5M,145.744,145.729,145.696,145.447,144.887

In [99]:
#checking the shape of our data

data.shape

(762, 10)

In [100]:
## saving our data

data.to_csv("./Data/data_collected.csv", index=False)